# -*- coding: utf-8 -*-
"""Day2.ipynb
erwrwere
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PjfICZvYQuy2ymzevNwRPQG0L_WTVk_c
"""

class Cars:
  def __init__ (self, brand, model, year, price):
    self.brand = brand
    self.model = model
    self.year = year
    self.price = price

  def get_brand(self):
    return self.brand
  def get_model(self):
    return self.model
  def get_year(self):
    return self.year
  def get_price(self):
    return self.price

car1 = Cars("Toyota", "Camry", 2020, 25000)
car2 = Cars("Honda", "Civic", 2019, 20000)

print(car1.get_brand())
print(car2.get_model())
print(car1.get_year())
print(car2.get_price())

class Bank:
  def __init__ (self, name, accountNumber, balance):
    self.name = name
    self.accountNumber = accountNumber
    self.balance = balance

  def deposit(self):
    amount = float(input("Enter amount to deposit: "))
    self.balance += amount
    print("Deposit successful. New balance: ", self.balance)

  def withdraw(self):
    amount = float(input("Enter amount to withdraw: "))
    if amount <= self.balance:
      self.balance -= amount
      print("Withdrawal successful. New balance: ", self.balance)
    else:
      print("Insufficient balance.")

  def bankFees(self):
    fees = 0.05 * self.balance
    self.balance -= fees
    print("Bank fees: ", fees)
    print("New balance: ", self.balance)

  def display(self):
    print("Name: ", self.name)
    print("Account Number: ", self.accountNumber)
    print("Balance: ", self.balance)

while True:
  menu = """
  1. Create Account
  2. Deposit
  3. Withdraw
  4. Bank Fees
  5. Display
  """
  print(menu)
  choice = int(input("Enter your choice: "))

  if choice == 1:
    name = input("Enter name: ")
    accountNumber = input("Enter account number: ")
    balance = float(input("Enter balance: "))
    bank = Bank(name, accountNumber, balance)
    bank.display()
  elif choice == 2:
    bank.deposit()
  elif choice == 3:
    bank.withdraw()
  elif choice == 4:
    bank.bankFees()
  elif choice == 5:
    bank.display()
